news_data = [{
        "domain":"https://sabq.org",
        "url":"https://sabq.org/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1-%D8%A7%D9%84%D8%B9%D8%A7%D9%84%D9%85",
        "news_url_xpath":"//div[contains(@class,'news-block')]//h2//@href",
        "title_xpath":"//div[contains(@itemprop,'headline')]/text()",
        "description_xpath":"//div[contains(@itemprop,'articleBody')]/p/text()",
        "image_xpath":"//div[contains(@class,'img-body')]//img/@src",
        "country": "sa/ar",
        "language": "arabic",
        "time_zone": "Asia/Riyadh",
        "category": "international"
       },
       {
        "domain":"https://sabq.org",
        "url":"https://sabq.org/%D8%B1%D9%8A%D8%A7%D8%B6%D8%A9",
        "news_url_xpath":"//div[contains(@class,'news-block')]//h2//@href",
        "title_xpath":"//div[contains(@itemprop,'headline')]/text()",
        "description_xpath":"//div[contains(@itemprop,'articleBody')]/p/text()",
        "image_xpath":"//div[contains(@class,'img-body')]//img/@src",
        "country": "sa/ar",
        "language": "arabic",
        "time_zone": "Asia/Riyadh",
        "category": "sports"
        },
       {
        "domain":"https://sabq.org",
        "url":"https://sabq.org/%D8%AA%D9%82%D9%86%D9%8A%D8%A9",
        "news_url_xpath":"//div[contains(@class,'news-block')]//h2//@href",
        "title_xpath":"//div[contains(@itemprop,'headline')]/text()",
        "description_xpath":"//div[contains(@itemprop,'articleBody')]/p/text()",
        "image_xpath":"//div[contains(@class,'img-body')]//img/@src",
        "country": "sa/ar",
        "language": "arabic",
        "time_zone": "Asia/Riyadh",
        "category": "technology"
       },
       {
        "domain":"https://sabq.org",
        "url":"https://sabq.org/%D8%B3%D9%8A%D8%A7%D8%AD%D8%A9",
        "news_url_xpath":"//div[contains(@class,'news-block')]//h2//@href",
        "title_xpath":"//div[contains(@itemprop,'headline')]/text()",
        "description_xpath":"//div[contains(@itemprop,'articleBody')]/p/text()",
        "image_xpath":"//div[contains(@class,'img-body')]//img/@src",
        "country": "sa/ar",
        "language": "arabic",
        "time_zone": "Asia/Riyadh",
        "category": "tourism"
       },
       {
        "domain":"https://www.sayidaty.net",
        "url":"https://www.sayidaty.net/category/main/%D8%B5%D8%AD%D8%A9-%D9%88%D8%B1%D8%B4%D8%A7%D9%82%D8%A9",
        "news_url_xpath":"//div[contains(@class,'thumbnail')]/a/@href",
        "title_xpath":"//div[contains(@class,'entry-title')]/h1/text()",
        "description_xpath":"//div[contains(@class,'entry-content')]/p/text()",
        "image_xpath":"//div[contains(@class,'slick-slide-inner')]/img/@data-lazy",
        "country": "sa/ar",
        "language": "arabic",
        "time_zone": "Asia/Riyadh",
        "category": "health"
       },
       {
        "domain":"https://www.sayidaty.net",
        "url":"https://www.sayidaty.net/category/main/%D9%84%D8%A7%D9%8A%D9%81-%D8%B3%D8%AA%D8%A7%D9%8A%D9%84",
        "news_url_xpath":"//div[contains(@class,'thumbnail')]/a/@href",
        "title_xpath":"//div[contains(@class,'entry-title')]/h1/text()",
        "description_xpath":"//div[contains(@class,'entry-content')]/p/text()",
        "image_xpath":"//div[contains(@class,'slick-slide-inner')]/img/@data-lazy",
        "country": "sa/ar",
        "language": "arabic",
        "time_zone": "Asia/Riyadh",
        "category": "life_style"
       },
       {
        "domain":"https://www.alyaum.com",
        "url":"https://www.alyaum.com/%D8%A7%D9%84%D9%85%D9%8A%D8%AF%D8%A7%D9%86",
        "news_url_xpath":"//div[contains(@class,'article')]//@href",
        "title_xpath":"//meta[contains(@property,'title')]/@content",
        "description_xpath":"//div[contains(@class,'aksa-articleBody')]/text()",
        "image_xpath":"//meta[contains(@property,'image')]/@content",
        "country": "sa/ar",
        "language": "arabic",
        "time_zone": "Asia/Riyadh",
        "category": "sports"
       },
       {
        "domain":"https://news.alnaeem.tv",
        "url":"https://news.alnaeem.tv/category/%d8%b9%d8%b1%d8%a8%d9%8a-%d9%88%d8%af%d9%88%d9%84%d9%8a/",
        "news_url_xpath":"//h2[contains(@class,'title')]/a/@href",
        "title_xpath":"//h1[contains(@class,'post-title')]/text()",
        "description_xpath":"//article[contains(@id,'post')]//p/text()",
        "image_xpath":"//figure[contains(@class,'single-featured-image')]/img/@src",
        "country": "sa/ar",
        "language": "arabic",
        "time_zone": "Asia/Riyadh",
        "category": "international"
       },
       {
        "domain":"https://albiladdaily.com",
        "url":"https://albiladdaily.com/category/%d8%af%d9%88%d9%84%d9%8a%d8%a9/",
        "news_url_xpath":"//h5[@class='entry-title']//a/@href",
        "title_xpath":"//h1[contains(@class,'entry-title')]/text()",
        "description_xpath":"//div[contains(@class,'entry-content')]/p/text()",
        "image_xpath":"//meta[contains(@property,'image')]/@content",
        "country": "sa/ar",
        "language": "arabic",
        "time_zone": "Asia/Riyadh",
        "category": "international"
       },
       {
        "domain":"https://albiladdaily.com",
        "url":"https://albiladdaily.com/category/%d8%aa%d9%83%d9%86%d9%88%d9%84%d9%88%d8%ac%d9%8a/",
        "news_url_xpath":"//h5[@class='entry-title']//a/@href",
        "title_xpath":"//h1[contains(@class,'entry-title')]/text()",
        "description_xpath":"//div[contains(@class,'entry-content')]/p/text()",
        "image_xpath":"//meta[contains(@property,'image')]/@content",
        "country": "sa/ar",
        "language": "arabic",
        "time_zone": "Asia/Riyadh",
        "category": "technology"
       },
       {
        "domain":"https://beta.alarabiya.net",
        "url":"https://beta.alarabiya.net/ar/saudi-today",
        "news_url_xpath":"//div[contains(@data-islisting,'listing')]//li[contains(@class,'list-item')]//@href",
        "title_xpath":"//h1[contains(@class,'headingInfo_title')]/text()",
        "description_xpath":"//div[contains(@id,'body-text')]/p/text()",
        "image_xpath":"//div[contains(@class,'image-wrapper')]/img/@src",
        "country": "sa/ar",
        "language": "arabic",
        "time_zone": "Asia/Riyadh",
        "category": "saudi"
       },
       {
        "domain":"https://www.masrawy.com",
        "url":"https://www.masrawy.com/channel/sports",
        "news_url_xpath":"//section[contains(@class,'pattern')]//div[contains(@class,'allItems')]/ul/li//@href",
        "title_xpath":"//div[contains(@class,'articleHeader')]/h1/text()",
        "description_xpath":"//div[contains(@class,'ArticleDetails details')]/p/text()",
        "image_xpath":"//img[contains(@id,'FeedImage')]/@src",
        "country": "eg/ar",
        "language": "arabic",
        "time_zone": "Egypt",
        "category": "sports"
       },
       {
        "domain":"https://www.masrawy.com",
        "url":"https://www.masrawy.com/channel/howa_w_hya",
        "news_url_xpath":"//section[contains(@class,'pattern')]//div[contains(@class,'allItems')]/ul/li//@href",
        "title_xpath":"//div[contains(@class,'articleHeader')]/h1/text()",
        "description_xpath":"//div[contains(@class,'ArticleDetails details')]/p/text()",
        "image_xpath":"//img[contains(@id,'FeedImage')]/@src",
        "country": "eg/ar",
        "language": "arabic",
        "time_zone": "Egypt",
        "category": "life_style"
       },
       {
        "domain":"https://www.masrawy.com",
        "url":"https://www.masrawy.com/News/News_PublicAffairs/section/202/",
        "news_url_xpath":"//section[contains(@class,'pattern')]//div[contains(@class,'allItems')]/ul/li//@href|//section[@class='listing']//ul/li/a[contains(@class,'item')]/@href",
        "title_xpath":"//div[contains(@class,'articleHeader')]/h1/text()",
        "description_xpath":"//div[contains(@class,'ArticleDetails details')]/p/text()",
        "image_xpath":"//img[contains(@id,'FeedImage')]/@src",
        "country": "eg/ar",
        "language": "arabic",
        "time_zone": "Egypt",
        "category": "international"
       },
       {
        "domain":"https://www.masrawy.com",
        "url":"https://www.masrawy.com/News/News_Egypt/section/35",
        "news_url_xpath":"//section[contains(@class,'pattern')]//div[contains(@class,'allItems')]/ul/li//@href|//section[@class='listing']//ul/li/a[contains(@class,'item')]/@href",
        "title_xpath":"//div[contains(@class,'articleHeader')]/h1/text()",
        "description_xpath":"//div[contains(@class,'ArticleDetails details')]/p/text()",
        "image_xpath":"//img[contains(@id,'FeedImage')]/@src",
        "country": "eg/ar",
        "language": "arabic",
        "time_zone": "Egypt",
        "category": "egypt"
       },
       {
        "domain":"https://www.masrawy.com",
        "url":"https://www.masrawy.com/channel/arts",
        "news_url_xpath":"//section[contains(@class,'pattern')]//div[contains(@class,'allItems')]/ul/li//@href",
        "title_xpath":"//div[contains(@class,'articleHeader')]/h1/text()",
        "description_xpath":"//div[contains(@class,'ArticleDetails details')]/p/text()",
        "image_xpath":"//img[contains(@id,'FeedImage')]/@src",
        "country": "eg/ar",
        "language": "arabic",
        "time_zone": "Egypt",
        "category": "entertainment"
       },
       {
        "domain":"https://www.masrawy.com",
        "url":"https://www.masrawy.com/channel/autos",
        "news_url_xpath":"//section[contains(@class,'pattern')]//div[contains(@class,'allItems')]/ul/li//@href",
        "title_xpath":"//div[contains(@class,'articleHeader')]/h1/text()",
        "description_xpath":"//div[contains(@class,'ArticleDetails details')]/p/text()",
        "image_xpath":"//img[contains(@id,'FeedImage')]/@src",
        "country": "eg/ar",
        "language": "arabic",
        "time_zone": "Egypt",
        "category": "automobiles"
       },
       {
        "domain":"https://www.masrawy.com",
        "url":"https://www.masrawy.com/News/News_Economy/section/206/",
        "news_url_xpath":"//section[contains(@class,'pattern')]//div[contains(@class,'allItems')]/ul/li//@href|//section[@class='listing']//ul/li/a[contains(@class,'item')]/@href",
        "title_xpath":"//div[contains(@class,'articleHeader')]/h1/text()",
        "description_xpath":"//div[contains(@class,'ArticleDetails details')]/p/text()",
        "image_xpath":"//img[contains(@id,'FeedImage')]/@src",
        "country": "eg/ar",
        "language": "arabic",
        "time_zone": "Egypt",
        "category": "business"
       },
       {
        "domain":"https://www.shorouknews.com",
        "url":"https://www.shorouknews.com/sports",
        "news_url_xpath":"//ul[contains(@class,'listing')]//div[contains(@class,'text')]//@href",
        "title_xpath":"//div[contains(@id,'sticky')]/h1/text()",
        "description_xpath":"//div[contains(@class,'eventContent')]/p/text()",
        "image_xpath":"//img[contains(@id,'Body_Body_imageMain')]/@src",
        "country": "eg/ar",
        "language": "arabic",
        "time_zone": "Egypt",
        "category": "sports"
       },
       {
        "domain":"https://www.shorouknews.com",
        "url":"https://www.shorouknews.com/auto",
        "news_url_xpath":"//ul[contains(@class,'listing')]//div[contains(@class,'text')]//@href",
        "title_xpath":"//div[contains(@id,'sticky')]/h1/text()",
        "description_xpath":"//div[contains(@class,'eventContent')]/p/text()",
        "image_xpath":"//img[contains(@id,'Body_Body_imageMain')]/@src",
        "country": "eg/ar",
        "language": "arabic",
        "time_zone": "Egypt",
        "category": "automobiles"
       },
       {
        "domain":"https://www.shorouknews.com",
        "url":"https://www.shorouknews.com/Economy",
        "news_url_xpath":"//ul[contains(@class,'listing')]//div[contains(@class,'text')]//@href",
        "title_xpath":"//div[contains(@id,'sticky')]/h1/text()",
        "description_xpath":"//div[contains(@class,'eventContent')]/p/text()",
        "image_xpath":"//img[contains(@id,'Body_Body_imageMain')]/@src",
        "country": "eg/ar",
        "language": "arabic",
        "time_zone": "Egypt",
        "category": "business"
       },
       {
        "domain":"https://www.shorouknews.com",
        "url":"https://www.shorouknews.com/Politics",
        "news_url_xpath":"//ul[contains(@class,'listing')]//div[contains(@class,'text')]//@href",
        "title_xpath":"//div[contains(@id,'sticky')]/h1/text()",
        "description_xpath":"//div[contains(@class,'eventContent')]/p/text()",
        "image_xpath":"//img[contains(@id,'Body_Body_imageMain')]/@src",
        "country": "eg/ar",
        "language": "arabic",
        "time_zone": "Egypt",
        "category": "international"
       },
       {
        "domain":"https://www.shorouknews.com",
        "url":"https://www.shorouknews.com/egypt",
        "news_url_xpath":"//ul[contains(@class,'listing')]//div[contains(@class,'text')]//@href",
        "title_xpath":"//div[contains(@id,'sticky')]/h1/text()",
        "description_xpath":"//div[contains(@class,'eventContent')]/p/text()",
        "image_xpath":"//img[contains(@id,'Body_Body_imageMain')]/@src",
        "country": "eg/ar",
        "language": "arabic",
        "time_zone": "Egypt",
        "category": "egypt"
       },
       {
        "domain":"https://www.shorouknews.com",
        "url":"https://www.shorouknews.com/tv",
        "news_url_xpath":"//ul[contains(@class,'listing')]//div[contains(@class,'text')]//@href",
        "title_xpath":"//div[contains(@id,'sticky')]/h1/text()",
        "description_xpath":"//div[contains(@class,'eventContent')]/p/text()",
        "image_xpath":"//img[contains(@id,'Body_Body_imageMain')]/@src",
        "country": "eg/ar",
        "language": "arabic",
        "time_zone": "Egypt",
        "category": "entertainment"
       },
       {
        "domain":"https://www.yallakora.com",
        "url":"https://www.yallakora.com",
        "news_url_xpath":"//section[contains(@class,'pattern1')]//a[contains(@class,'link')]/@href",
        "title_xpath":"//h1[contains(@class,'artclHdline')]/text()",
        "description_xpath":"//div[contains(@class,'ArticleDetails details')]/p/text()",
        "image_xpath":"//img[contains(@id,'FeedImage')]/@data-src",
        "country": "eg/ar",
        "language": "arabic",
        "time__zone": "Egypt",
        "category": "sports"
        },
        {
        "domain":"https://arabic.rt.com",
        "url":"https://arabic.rt.com/health",
        "news_url_xpath":"//div[contains(@class,'news-partition')]/ul/li/div[contains(@class,'cell')]//@href|//div[contains(@class,'list-news')]//ul/li/div[contains(@class,'element')]//@href",
        "title_xpath":"//h1[contains(@class,'heading')]/text()",
        "description_xpath":"//div[contains(@class,'article')]/p/text()",
        "image_xpath":"//div[contains(@class,'photo__wrapper')]//img/@data-src",
        "country": "eg/ar",
        "language": "arabic",
        "time_zone": "Egypt",
        "category": "health"
       },
       {
        "domain":"https://arabic.rt.com",
        "url":"https://arabic.rt.com/technology/",
        "news_url_xpath":"//div[contains(@class,'news-partition')]/ul/li/div[contains(@class,'cell')]//@href|//div[contains(@class,'list-news')]//ul/li/div[contains(@class,'element')]//@href",
        "title_xpath":"//h1[contains(@class,'heading')]/text()",
        "description_xpath":"//div[contains(@class,'article')]/p/text()",
        "image_xpath":"//div[contains(@class,'photo__wrapper')]//img/@data-src",
        "country": "eg/ar",
        "language": "arabic",
        "time_zone": "Egypt",
        "category": "technology"
       },
       {
        "domain":"https://arabic.rt.com",
        "url":"https://arabic.rt.com/world",
        "news_url_xpath":"//div[contains(@class,'news-partition')]/ul/li/div[contains(@class,'cell')]//@href|//div[contains(@class,'list-news')]//ul/li/div[contains(@class,'element')]//@href",
        "title_xpath":"//h1[contains(@class,'heading')]/text()",
        "description_xpath":"//div[contains(@class,'article')]/p/text()",
        "image_xpath":"//div[contains(@class,'photo__wrapper')]//img/@data-src",
        "country": "eg/ar",
        "language": "arabic",
        "time_zone": "Egypt",
        "category": "international"
       },
       {
        "domain":"https://arabic.rt.com",
        "url":"https://arabic.rt.com/culture/",
        "news_url_xpath":"//div[contains(@class,'news-partition')]/ul/li/div[contains(@class,'cell')]//@href|//div[contains(@class,'list-news')]//ul/li/div[contains(@class,'element')]//@href",
        "title_xpath":"//h1[contains(@class,'heading')]/text()",
        "description_xpath":"//div[contains(@class,'article')]/p/text()",
        "image_xpath":"//div[contains(@class,'photo__wrapper')]//img/@data-src",
        "country": "eg/ar",
        "language": "arabic",
        "time_zone": "Egypt",
        "category": "entertainment"
       },
       {
        "domain":"https://arabic.rt.com",
        "url":"https://arabic.rt.com/car",
        "news_url_xpath":"//div[contains(@class,'news-partition')]/ul/li/div[contains(@class,'cell')]//@href|//div[contains(@class,'list-news')]//ul/li/div[contains(@class,'element')]//@href",
        "title_xpath":"//h1[contains(@class,'heading')]/text()",
        "description_xpath":"//div[contains(@class,'article')]/p/text()",
        "image_xpath":"//div[contains(@class,'photo__wrapper')]//img/@data-src",
        "country": "eg/ar",
        "language": "arabic",
        "time_zone": "Egypt",
        "category": "automobiles"
       },
       {
        "domain":"https://www.alkhaleej.ae",
        "url":"https://www.alkhaleej.ae/%D8%B1%D9%8A%D8%A7%D8%B6%D8%A9",
        "news_url_xpath":"//div[contains(@class,'articles-list')]//div[contains(@class,'views-row')]//@href",
        "title_xpath":"//h1[contains(@class,'page-title')]/text()",
        "description_xpath":"//div[contains(@class,'field--name-body')]/p/text()",
        "image_xpath":"//picture//img[contains(@class,'media')]/@data-src",
        "country": "ae/ar",
        "language": "arabic",
        "time_zone": "Asia/Dubai",
        "category": "sports"
       },
       {
        "domain":"https://www.alkhaleej.ae",
        "url":"https://www.alkhaleej.ae/%D8%B3%D9%8A%D8%A7%D8%AD%D8%A9-%D9%88%D8%B7%D9%8A%D8%B1%D8%A7%D9%86",
        "news_url_xpath":"//div[contains(@class,'articles-list')]//div[contains(@class,'views-row')]//@href",
        "title_xpath":"//h1[contains(@class,'page-title')]/text()",
        "description_xpath":"//div[contains(@class,'field--name-body')]/p/text()",
        "image_xpath":"//picture//img[contains(@class,'media')]/@data-src",
        "country": "ae/ar",
        "language": "arabic",
        "time_zone": "Asia/Dubai",
        "category": "tourism"
        },
        {
        "domain":"https://www.alkhaleej.ae",
        "url":"https://www.alkhaleej.ae/%D8%AA%D9%82%D9%86%D9%8A%D8%A9-%D9%88%D8%B3%D9%8A%D8%A7%D8%B1%D8%A7%D8%AA",
        "news_url_xpath":"//div[contains(@class,'articles-list')]//div[contains(@class,'views-row')]//@href",
        "title_xpath":"//h1[contains(@class,'page-title')]/text()",
        "description_xpath":"//div[contains(@class,'field--name-body')]/p/text()",
        "image_xpath":"//picture//img[contains(@class,'media')]/@data-src",
        "country": "ae/ar",
        "language": "arabic",
        "time_zone": "Asia/Dubai",
        "category": "technology"
        },
        {
        "domain":"https://www.alkhaleej.ae",
        "url":"https://www.alkhaleej.ae/%D9%85%D8%A7%D9%84-%D9%88%D8%A3%D8%B9%D9%85%D8%A7%D9%84",
        "news_url_xpath":"//div[contains(@class,'articles-list')]//div[contains(@class,'views-row')]//@href",
        "title_xpath":"//h1[contains(@class,'page-title')]/text()",
        "description_xpath":"//div[contains(@class,'field--name-body')]/p/text()",
        "image_xpath":"//picture//img[contains(@class,'media')]/@data-src",
        "country": "ae/ar",
        "language": "arabic",
        "time_zone": "Asia/Dubai",
        "category": "business"
        },
        {
        "domain":"https://www.albayan.ae",
        "url":"https://www.albayan.ae/health/health-happiness",
        "news_url_xpath":"//li[contains(@class,'el')]/article//@href",
        "title_xpath":"//h1[contains(@class,'title')]/text()",
        "description_xpath":"//div[@id='articledetails']/p[not(contains(@class,'follow-google'))]/text()",
        "image_xpath":"//figure[contains(@class,'detailsmedia')]//@src",
        "country": "ae/ar",
        "language": "arabic",
        "time_zone": "Asia/Dubai",
        "category": "health"
       },
       {
        "domain":"https://www.albayan.ae",
        "url":"https://www.albayan.ae/economy/tourism",
        "news_url_xpath":"//li[contains(@class,'el')]/article//@href",
        "title_xpath":"//h1[contains(@class,'title')]/text()",
        "description_xpath":"//div[@id='articledetails']/p[not(contains(@class,'follow-google'))]/text()",
        "image_xpath":"//figure[contains(@class,'detailsmedia')]//@src",
        "country": "ae/ar",
        "language": "arabic",
        "time_zone": "Asia/Dubai",
        "category": "tourism"
       },
       {
        "domain":"https://www.albayan.ae",
        "url":"https://www.albayan.ae/economy/companies-businesses",
        "news_url_xpath":"//li[contains(@class,'el')]/article//@href",
        "title_xpath":"//h1[contains(@class,'title')]/text()",
        "description_xpath":"//div[@id='articledetails']/p[not(contains(@class,'follow-google'))]/text()",
        "image_xpath":"//figure[contains(@class,'detailsmedia')]//@src",
        "country": "ae/ar",
        "language": "arabic",
        "time_zone": "Asia/Dubai",
        "category": "business"
       },
       {
        "domain":"https://www.albayan.ae",
        "url":"https://www.albayan.ae/one-world",
        "news_url_xpath":"//li[contains(@class,'el')]/article//@href",
        "title_xpath":"//h1[contains(@class,'title')]/text()",
        "description_xpath":"//div[@id='articledetails']/p[not(contains(@class,'follow-google'))]/text()",
        "image_xpath":"//figure[contains(@class,'detailsmedia')]//@src",
        "country": "ae/ar",
        "language": "arabic",
        "time_zone": "Asia/Dubai",
        "category": "international"
       },
       {
        "domain":"https://www.albayan.ae",
        "url":"https://www.albayan.ae/across-the-uae",
        "news_url_xpath":"//li[contains(@class,'el')]/article//@href",
        "title_xpath":"//h1[contains(@class,'title')]/text()",
        "description_xpath":"//div[@id='articledetails']/p[not(contains(@class,'follow-google'))]/text()",
        "image_xpath":"//figure[contains(@class,'detailsmedia')]//@src",
        "country": "ae/ar",
        "language": "arabic",
        "time_zone": "Asia/Dubai",
        "category": "uae"
       }
]