news_data = [{
        "domain":"https://sabq.org",
        "url":"https://sabq.org/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1-%D8%A7%D9%84%D8%B9%D8%A7%D9%84%D9%85",
        "news_url_xpath":"//div[contains(@class,'news-block')]//h2//@href",
        "title_xpath":"//div[contains(@itemprop,'headline')]/text()",
        "description_xpath":"//div[contains(@itemprop,'articleBody')]/p/text()",
        "image_xpath":"//div[contains(@class,'img-body')]//img/@src",
        "country": "sa/ar",
        "language": "arabic",
        "time_zone": "Asia/Riyadh",
        "category": "world_news"
       },
       {
        "domain":"https://sabq.org",
        "url":"https://sabq.org/%D8%AA%D9%82%D9%86%D9%8A%D8%A9",
        "news_url_xpath":"//div[contains(@class,'news-block')]//h2//@href",
        "title_xpath":"//div[contains(@itemprop,'headline')]/text()",
        "description_xpath":"//div[contains(@itemprop,'articleBody')]/p/text()",
        "image_xpath":"//div[contains(@class,'img-body')]//img/@src",
        "country": "sa/ar",
        "language": "arabic",
        "time_zone": "Asia/Riyadh",
        "category": "technology"
       },
       {
        "domain":"https://sabq.org",
        "url":"https://sabq.org/%D8%B3%D9%8A%D8%A7%D8%AD%D8%A9",
        "news_url_xpath":"//div[contains(@class,'news-block')]//h2//@href",
        "title_xpath":"//div[contains(@itemprop,'headline')]/text()",
        "description_xpath":"//div[contains(@itemprop,'articleBody')]/p/text()",
        "image_xpath":"//div[contains(@class,'img-body')]//img/@src",
        "country": "sa/ar",
        "language": "arabic",
        "time_zone": "Asia/Riyadh",
        "category": "tourism"
       },
       {
        "domain":"https://www.sayidaty.net",
        "url":"https://www.sayidaty.net/category/main/%D8%B5%D8%AD%D8%A9-%D9%88%D8%B1%D8%B4%D8%A7%D9%82%D8%A9",
        "news_url_xpath":"//div[contains(@class,'thumbnail')]/a/@href",
        "title_xpath":"//div[contains(@class,'entry-title')]/h1/text()",
        "description_xpath":"//div[contains(@class,'entry-content')]/p/text()",
        "image_xpath":"//div[contains(@class,'slick-slide-inner')]/img/@data-lazy",
        "country": "sa/ar",
        "language": "arabic",
        "time_zone": "Asia/Riyadh",
        "category": "health"
       },
       {
        "domain":"https://www.sayidaty.net",
        "url":"https://www.sayidaty.net/category/main/%D9%84%D8%A7%D9%8A%D9%81-%D8%B3%D8%AA%D8%A7%D9%8A%D9%84",
        "news_url_xpath":"//div[contains(@class,'thumbnail')]/a/@href",
        "title_xpath":"//div[contains(@class,'entry-title')]/h1/text()",
        "description_xpath":"//div[contains(@class,'entry-content')]/p/text()",
        "image_xpath":"//div[contains(@class,'slick-slide-inner')]/img/@data-lazy",
        "country": "sa/ar",
        "language": "arabic",
        "time_zone": "Asia/Riyadh",
        "category": "life_style"
       },
       {
        "domain":"https://www.alyaum.com",
        "url":"https://www.alyaum.com/%D8%A7%D9%84%D9%85%D9%8A%D8%AF%D8%A7%D9%86",
        "news_url_xpath":"//div[contains(@class,'article')]//@href",
        "title_xpath":"//meta[contains(@property,'title')]/@content",
        "description_xpath":"//div[contains(@class,'aksa-articleBody')]/text()",
        "image_xpath":"//meta[contains(@property,'image')]/@content",
        "country": "sa/ar",
        "language": "arabic",
        "time_zone": "Asia/Riyadh",
        "category": "sports"
       },
       {
        "domain":"https://news.alnaeem.tv",
        "url":"https://news.alnaeem.tv/category/%d8%b9%d8%b1%d8%a8%d9%8a-%d9%88%d8%af%d9%88%d9%84%d9%8a/",
        "news_url_xpath":"//h2[contains(@class,'title')]/a/@href",
        "title_xpath":"//h1[contains(@class,'post-title')]/text()",
        "description_xpath":"//article[contains(@id,'post')]//p/text()",
        "image_xpath":"//figure[contains(@class,'single-featured-image')]/img/@src",
        "country": "sa/ar",
        "language": "arabic",
        "time_zone": "Asia/Riyadh",
        "category": "international"
       },
       {
        "domain":"https://albiladdaily.com",
        "url":"https://albiladdaily.com/category/%d8%af%d9%88%d9%84%d9%8a%d8%a9/",
        "news_url_xpath":"//h5[@class='entry-title']//a/@href",
        "title_xpath":"//h1[contains(@class,'entry-title')]/text()",
        "description_xpath":"//div[contains(@class,'entry-content')]/p/text()",
        "image_xpath":"//meta[contains(@property,'image')]/@content",
        "country": "sa/ar",
        "language": "arabic",
        "time_zone": "Asia/Riyadh",
        "category": "international"
       },
       {
        "domain":"https://albiladdaily.com",
        "url":"https://albiladdaily.com/category/%d8%aa%d9%83%d9%86%d9%88%d9%84%d9%88%d8%ac%d9%8a/",
        "news_url_xpath":"//h5[@class='entry-title']//a/@href",
        "title_xpath":"//h1[contains(@class,'entry-title')]/text()",
        "description_xpath":"//div[contains(@class,'entry-content')]/p/text()",
        "image_xpath":"//meta[contains(@property,'image')]/@content",
        "country": "sa/ar",
        "language": "arabic",
        "time_zone": "Asia/Riyadh",
        "category": "tecnology"
       },
       {
        "domain":"https://beta.alarabiya.net",
        "url":"https://beta.alarabiya.net/ar/saudi-today",
        "news_url_xpath":"//div[contains(@data-islisting,'listing')]//li[contains(@class,'list-item')]//@href",
        "title_xpath":"//h1[contains(@class,'headingInfo_title')]/text()",
        "description_xpath":"//div[contains(@id,'body-text')]/p/text()",
        "image_xpath":"//div[contains(@class,'image-wrapper')]/img/@src",
        "country": "sa/ar",
        "language": "arabic",
        "time_zone": "Asia/Riyadh",
        "category": "saudi"
       }
]